import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100`}>
        <main className="overflowed text-gray-1200 mx-auto my-12 max-w-[1144px] px-4 antialiased sm:my-32 md:my-[3px] md:mb-40 md:px-6">
          {children}
        </main>
      </body>
    </html>
  );
}
